apiVersion: tmax.hypercloud.com/v1
kind: VirtualRouter
metadata:
  name: virtualrouter1
  namespace: virtualrouter
spec:
  deploymentName: example-virtualrouter
  replicas: 1
  vlanNumber: 210
  internalIP: 10.10.10.11
  internalNetmask: 255.255.255.0
  externalIP: 192.168.8.153
  externalNetmask: 255.255.255.0
  gatewayIP: 192.168.8.2
  internalCIDR: "10.10.10.0/24"
  image: 10.0.0.4:5000/virtualrouter:v0.1.0
  nodeSelector:
    - key: app
      value: test